-- MySQL Script generated by MySQL Workbench
-- mar 27 jun 2023 12:37:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen2021
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Examen2021` ;

-- -----------------------------------------------------
-- Schema Examen2021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen2021` ;
USE `Examen2021` ;

-- -----------------------------------------------------
-- Table `Examen2021`.`Generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Generos` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Generos` (
  `idGenero` CHAR(10) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`Direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Direcciones` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Direcciones` (
  `idDireccion` INT NOT NULL,
  `calleYNumero` VARCHAR(50) NOT NULL,
  `municipio` VARCHAR(20) NOT NULL,
  `codigoPostal` VARCHAR(10) NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idDireccion`),
  UNIQUE INDEX `calleYNumero_UNIQUE` (`calleYNumero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`Peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Peliculas` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Peliculas` (
  `idPelicula` INT NOT NULL,
  `titulo` VARCHAR(128) NOT NULL,
  `estreno` INT NULL,
  `duracion` INT NULL,
  `clasificacion` ENUM('G', 'PG', 'PG-13', 'R', 'NC-17') NOT NULL DEFAULT 'G',
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Personal` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Personal` (
  `idPersonal` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `idDireccion` INT NOT NULL,
  `correo` VARCHAR(50) NULL,
  `estado` ENUM('E', 'D') NOT NULL DEFAULT 'E',
  PRIMARY KEY (`idPersonal`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_Personal_Direcciones1_idx` (`idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_Direcciones1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `Examen2021`.`Direcciones` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`Sucursales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Sucursales` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Sucursales` (
  `idSucursal` CHAR(10) NOT NULL,
  `idGerente` INT NOT NULL,
  `idDireccion` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursales_Personal1_idx` (`idGerente` ASC) VISIBLE,
  INDEX `fk_Sucursales_Direcciones1_idx` (`idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursales_Personal1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `Examen2021`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursales_Direcciones1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `Examen2021`.`Direcciones` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`Inventario` (
  `idInventario` INT NOT NULL,
  `idPelicula` INT NOT NULL,
  `idSucursal` CHAR(10) NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Peliculas1_idx` (`idPelicula` ASC) VISIBLE,
  INDEX `fk_Inventario_Sucursales1_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Peliculas1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `Examen2021`.`Peliculas` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Sucursales1`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Examen2021`.`Sucursales` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2021`.`GenerosDePeliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Examen2021`.`GenerosDePeliculas` ;

CREATE TABLE IF NOT EXISTS `Examen2021`.`GenerosDePeliculas` (
  `idPelicula` INT NOT NULL,
  `idGenero` CHAR(10) NOT NULL,
  PRIMARY KEY (`idPelicula`, `idGenero`),
  INDEX `fk_Generos_has_Peliculas_Peliculas1_idx` (`idPelicula` ASC) VISIBLE,
  INDEX `fk_Generos_has_Peliculas_Generos_idx` (`idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Generos_has_Peliculas_Generos`
    FOREIGN KEY (`idGenero`)
    REFERENCES `Examen2021`.`Generos` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Generos_has_Peliculas_Peliculas1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `Examen2021`.`Peliculas` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
