-- MySQL Script generated by MySQL Workbench
-- lun 26 jun 2023 20:34:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Parcial2022
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Parcial2022` ;

-- -----------------------------------------------------
-- Schema Parcial2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Parcial2022` ;
USE `Parcial2022` ;

-- -----------------------------------------------------
-- Table `Parcial2022`.`Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Autores` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Autores` (
  `idAutor` VARCHAR(11) NOT NULL,
  `apellido` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `telefono` CHAR(12) NOT NULL DEFAULT 'UNKNOWN',
  `domicilio` VARCHAR(40) NULL,
  `ciudad` VARCHAR(20) NULL,
  `estado` CHAR(2) NULL,
  `codigoPostal` CHAR(5) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`Editoriales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Editoriales` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Editoriales` (
  `idEditorial` CHAR(4) NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `ciudad` VARCHAR(20) NULL,
  `estado` CHAR(2) NULL,
  `pais` VARCHAR(30) NOT NULL DEFAULT 'USA',
  PRIMARY KEY (`idEditorial`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`Tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Tiendas` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Tiendas` (
  `idTienda` CHAR(4) NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `domicilio` VARCHAR(40) NULL,
  `ciudad` VARCHAR(20) NULL,
  `estado` CHAR(2) NULL,
  `codigoPostal` CHAR(5) NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`Titulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Titulos` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Titulos` (
  `idTitulo` VARCHAR(6) NOT NULL,
  `titulo` VARCHAR(80) NOT NULL,
  `genero` CHAR(12) NOT NULL DEFAULT 'UNDECIDED',
  `idEditorial` CHAR(4) NOT NULL,
  `precio` DECIMAL(8,2) NULL CHECK (precio>0),
  `sinopsis` VARCHAR(200) NULL,
  `fechaPublicacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTitulo`),
  INDEX `fk_Titulos_Editoriales1_idx` (`idEditorial` ASC) VISIBLE,
  CONSTRAINT `fk_Titulos_Editoriales1`
    FOREIGN KEY (`idEditorial`)
    REFERENCES `Parcial2022`.`Editoriales` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`TitulosDelAutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`TitulosDelAutor` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`TitulosDelAutor` (
  `idAutor` VARCHAR(11) NOT NULL,
  `idTitulo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idAutor`, `idTitulo`),
  INDEX `fk_Titulos_has_Autores_Autores1_idx` (`idAutor` ASC) VISIBLE,
  INDEX `fk_Titulos_has_Autores_Titulos_idx` (`idTitulo` ASC) VISIBLE,
  CONSTRAINT `fk_Titulos_has_Autores_Titulos`
    FOREIGN KEY (`idTitulo`)
    REFERENCES `Parcial2022`.`Titulos` (`idTitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Titulos_has_Autores_Autores1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `Parcial2022`.`Autores` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Ventas` (
  `codigoVenta` VARCHAR(20) NOT NULL,
  `idTienda` CHAR(4) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `tipo` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`codigoVenta`),
  INDEX `fk_Ventas_Tiendas1_idx` (`idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Tiendas1`
    FOREIGN KEY (`idTienda`)
    REFERENCES `Parcial2022`.`Tiendas` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parcial2022`.`Detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parcial2022`.`Detalles` ;

CREATE TABLE IF NOT EXISTS `Parcial2022`.`Detalles` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `codigoVenta` VARCHAR(20) NOT NULL,
  `idTitulo` VARCHAR(6) NOT NULL,
  `cantidad` SMALLINT NOT NULL CHECK (cantidad>0),
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_Detalles_Ventas1_idx` (`codigoVenta` ASC) VISIBLE,
  INDEX `fk_Detalles_Titulos1_idx` (`idTitulo` ASC) VISIBLE,
  CONSTRAINT `fk_Detalles_Ventas1`
    FOREIGN KEY (`codigoVenta`)
    REFERENCES `Parcial2022`.`Ventas` (`codigoVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalles_Titulos1`
    FOREIGN KEY (`idTitulo`)
    REFERENCES `Parcial2022`.`Titulos` (`idTitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
